version: '3'
services:
  postgres-test:
    image: postgres:12-alpine
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run
    # Adapted from https://github.com/getredash/redash/blob/6149e00/docker-compose.yml#L42
    command: 'postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=test
    ports:
      - 5432:5432

  redis:
    image: redis:5.0.7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379

  test:
    build: .
    command: ./node_modules/.bin/jest --watchAll=${JEST_WATCH:-false} --runInBand
    restart: 'no'
    tty: ${JEST_WATCH-false}
    stdin_open: ${JEST_WATCH-false}
    volumes:
      - ./src:/usr/app/src:delegated
      - ./test:/usr/app/test:delegated
    env_file:
      - ./.env
    depends_on:
      - postgres-test
      - redis
    environment:
      - NODE_ENV=test
      - POSTGRES_HOST=postgres-test
      - POSTGRES_DB=test
