/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2021-05-30 22:14:08 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:5432/postgres -C -t knex_migrations -t discount_rules -t users -t products -t knex_migrations_lock -s public
 *
 */

export type EnumDiscountRulesType = 'bogof' | 'bulk';

export namespace KnexMigrationsFields {
  export type id = number;
  export type name = string | null;
  export type batch = number | null;
  export type migrationTime = Date | null;

}

export interface KnexMigrations {
  id: KnexMigrationsFields.id;
  name: KnexMigrationsFields.name;
  batch: KnexMigrationsFields.batch;
  migrationTime: KnexMigrationsFields.migrationTime;

}

export namespace DiscountRulesFields {
  export type id = number;
  export type productCode = string;
  export type type = EnumDiscountRulesType;
  export type quantity = number;
  export type discount = number;
  export type createdAt = Date;
  export type updatedAt = Date;

}

export interface DiscountRules {
  id: DiscountRulesFields.id;
  productCode: DiscountRulesFields.productCode;
  type: DiscountRulesFields.type;
  quantity: DiscountRulesFields.quantity;
  discount: DiscountRulesFields.discount;
  createdAt: DiscountRulesFields.createdAt;
  updatedAt: DiscountRulesFields.updatedAt;

}

export namespace UsersFields {
  export type id = number;
  export type email = string;
  export type passwordHash = string;
  export type firstName = string | null;
  export type lastName = string | null;
  export type createdAt = Date | null;
  export type updatedAt = Date | null;

}

export interface Users {
  id: UsersFields.id;
  email: UsersFields.email;
  passwordHash: UsersFields.passwordHash;
  firstName: UsersFields.firstName;
  lastName: UsersFields.lastName;
  createdAt: UsersFields.createdAt;
  updatedAt: UsersFields.updatedAt;

}

export namespace ProductsFields {
  export type id = number;
  export type code = string;
  export type name = string;
  export type price = number;
  export type createdAt = Date;
  export type updatedAt = Date;

}

export interface Products {
  id: ProductsFields.id;
  code: ProductsFields.code;
  name: ProductsFields.name;
  price: ProductsFields.price;
  createdAt: ProductsFields.createdAt;
  updatedAt: ProductsFields.updatedAt;

}

export namespace KnexMigrationsLockFields {
  export type index = number;
  export type isLocked = number | null;

}

export interface KnexMigrationsLock {
  index: KnexMigrationsLockFields.index;
  isLocked: KnexMigrationsLockFields.isLocked;

}
